name: Bug Report
description: Report a problem with Enhanced SunPower integration
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Just need a few quick details to help diagnose the issue.

        **Before filing a bug report, please:**
        1. ✅ **Reboot your PVS** - Power cycle the PVS and wait 2-3 minutes for it to fully restart
        2. ✅ **Restart Home Assistant** - Settings → System → Restart
        3. ✅ **Check if the issue persists** - Many issues resolve after a fresh restart

        If the problem continues after rebooting, please provide the details below:

  - type: dropdown
    id: integration-version
    attributes:
      label: Integration Version
      description: What version are you running?
      options:
        - v2025.11.2 (latest)
        - v2025.10.7 or older
        - Not sure
      options:
        - v2025.11.1 (latest)
        - v2025.10.7 or older
        - Not sure
      options:
        - v2025.10.20 (latest)
        - v2025.10.19
        - v2025.10.18
        - v2025.10.17
        - v2025.10.16
        - v2025.10.15
        - v2025.10.14
        - v2025.10.13
        - v2025.10.12
        - v2025.10.11
        - v2025.10.10
        - v2025.10.9
        - v2025.10.8
        - v2025.10.7 or older
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: pvs-model
    attributes:
      label: PVS Model
      description: Which PVS do you have?
      options:
        - PVS5
        - PVS6
        - Not sure
    validations:
      required: true

  - type: input
    id: firmware-build
    attributes:
      label: PVS Firmware BUILD (optional)
      description: "Found at: Settings → Devices & Services → Enhanced SunPower → (device) → Firmware"
      placeholder: "e.g., 61845, 58000"
    validations:
      required: false

  - type: dropdown
    id: battery-system
    attributes:
      label: Do you have a battery system?
      description: SunVault, ESS, or any battery storage connected to PVS
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: What's going wrong?
      placeholder: Tell us what you're seeing...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots (optional)
      description: |
        Copy/paste logs or attach screenshots if helpful.
        **Find logs:** Settings → System → Logs → Search for "sunpower"
      render: shell
    validations:
      required: false
