name: Feature Request
description: Suggest an idea for Enhanced SunPower integration
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? Let us know!

  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added?
      description: Describe the feature you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional details (optional)
      description: Screenshots, examples, or other context
      placeholder: Any other relevant details
    validations:
      required: false
