name: "HACS Validation"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
